[nfs]
172.31.25.225 ansible_ssh_user='ec2-user'

[webservers]
172.31.25.99  ansible_ssh_user='ec2-user'
172.31.31.235 ansible_ssh_user='ec2-user'

[db]
172.31.18.126 ansible_ssh_user='ec2-user'

[lb]
172.31.16.172 ansible_ssh_user='ubuntu'